# Clippy 配置：提高代码检查严格程度
# 参考：https://rust-lang.github.io/rust-clippy/master/index.html#configuration

# 降低复杂度阈值（更严格）
cognitive-complexity-threshold = 15     # 默认 25，越小越严格
too-many-arguments-threshold = 6        # 默认 7，越小越严格
type-complexity-threshold = 200         # 默认 250，越小越严格
enum-variant-size-threshold = 128       # 默认 200，越小越严格
large-error-threshold = 128             # 更早提示错误类型过大

# 测试中也避免使用 unwrap/expect（更严格）
allow-unwrap-in-tests = false

# 如果需要，可在此设置 MSRV（最低支持的 Rust 版本）以获得更准确的建议
msrv = "1.89"